apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  # labels:
  #   web-app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      web-app: mongo-express
  template:
    metadata:
      labels:
        web-app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-passsword
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url

--- # External Service
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    web-app: mongo-express
  type: LoadBalancer #external service
  ports:
    - protocol: TCP
      port: 8081 #service port
      targetPort: 8081
      nodePort: 30000 #30000-32767

