apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  # labels:
  #   db: mongodb
spec:
  replicas: 1
  selector:
    matchLabels: #pods that the deployment is for
      db: mongodb
  # POD Config
  template: 
    metadata:
      labels:
        db: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-passsword

--- # New document -> service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  #type: ClusterIp -> default internal
  selector:
    db: mongodb
  ports:
    - protocol: TCP
      port: 27017 #service port
      targetPort: 27017
